### ISSUE TITLE
Mal negocio del mercado en la base de datos

### ISSUE THREAD

**Issue by alvarodg** [JsAntoPe/MedievalGame#8]
El mercado que está guardado en la base de datos tiene unos valores que causan que a partir de cierto nivel empiece a regalar recursos y no puedo modificar la base de datos en este momento. Que alguien lo cambie a:
{level: 1, name: 'market', upgradeCostWood: [1, 1, 1, 1, 1], upgradeCostGold: [1, 1, 1, 1, 1],
    basePurchasePrice: [2, 2], baseSalePrices: [0.5, 0.5], levelGrowth: 0.1, purchaseMod: [1, 1], saleMod: [1, 1]}
(Por ejemplo)

**Comment by JsAntoPe** [comment]
Listo cambiado al ejemplo que has puesto. Si hace falta cambiar despues todos, hay que irse a la clase del enlace con la api REST de la base de datos de cada uno y ademas cambiarlo en la base de datos.
